name: "Valtx SDD Gates"
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  gates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ejecutar Gates de Gobernanza
        uses: MiguelGironAltamirano/valtx-sdd-core@main
        env:
          VALTX_HUB_URL: https://api.valtx-sdd.duckdns.org
        with:
          phase: merge
